# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardBox' do
  # Comment the next line if you don't want to use dynamic frameworks use_frameworks!
  # Pods for CardBox
use_frameworks!

pod 'FoldingCell' # for later
pod 'RealmSwift', '~> 10.25.0' # for Card data

  target 'CardBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardBoxUITests' do
    # Pods for UItesting
  end

end
