# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardBox' do
  # Comment the next line if you don't want to use dynamic frameworks use_frameworks!
pod 'FoldingCell'
pod 'RealmSwift'

  # Pods for CardBox

  target 'CardBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardBoxUITests' do
    # Pods for testing
  end

end
